# Minimal Hyprland config

monitor=,preferred,auto,1.25

env = XCURSOR_SIZE,24

input {
    kb_layout = us
    follow_mouse = 1
    touchpad {
        natural_scroll = false
    }
    sensitivity = 0
}

general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2
    col.active_border = rgba(88c0d0ee)
    col.inactive_border = rgba(4c566aee)
    layout = dwindle
}

dwindle {
    # Always place new tiled windows to the right/bottom.
    force_split = 2
}

decoration {
    rounding = 6
}

animations {
    enabled = true
}

# Keep launchers as floating centered windows.
windowrule = float on, match:class ^(wofi)$
windowrule = center on, match:class ^(wofi)$

exec-once = waybar
exec-once = dunst
exec-once = hyprpaper
exec-once = bash -lc "sleep 1 && ~/.config/hypr/scripts/set-random-wallpaper.sh"

$mod = SUPER
$terminal = kitty
$browser = google-chrome-stable

source = ~/.config/hypr/keybinds.conf
