# Minimal Hyprland config

monitor=,preferred,auto,1.25

env = XCURSOR_SIZE,24

input {
    kb_layout = us
    follow_mouse = 1
    touchpad {
        natural_scroll = false
    }
    sensitivity = 0
}

general {
    gaps_in = 1
    gaps_out = 2
    border_size = 0
    col.active_border = rgba(b08cffee)
    col.inactive_border = rgba(2a3050cc)
    layout = dwindle
}

dwindle {
    # Always place new tiled windows to the right/bottom.
    force_split = 2
}

decoration {
    rounding = 6
    active_opacity = 0.94
    inactive_opacity = 0.88

    blur {
        enabled = true
        size = 6
        passes = 2
        new_optimizations = true
    }

    shadow {
        enabled = true
        range = 10
        render_power = 3
        color = rgba(00000055)
    }
}

animations {
    enabled = true
}

# Keep launchers as floating centered windows.
windowrule = float on, match:class ^(wofi)$
windowrule = center on, match:class ^(wofi)$

exec-once = waybar
exec-once = dunst
exec-once = hyprpaper
exec-once = bash -lc "sleep 1 && ~/.config/hypr/scripts/set-random-wallpaper.sh"

$mod = SUPER
$terminal = kitty
$browser = google-chrome-stable

source = ~/.config/hypr/keybinds.conf
