font_family JetBrainsMono Nerd Font
font_size 10.5

confirm_os_window_close 0
enable_audio_bell no

background #1e222a
foreground #e6e6e6
selection_background #3b4252
selection_foreground #eceff4

cursor #88c0d0
cursor_text_color #1e222a
